### ISSUE TITLE
[Feature Request] Forwarding scoreboard toggle

### ISSUE THREAD

**Issue by Whitescan** [NEZNAMY/TAB-Bridge#14]
What?
Add the function so player's can toggle their scoreboard with a bukkit command.

Why?
If the server wants to provide a GUI (inventory) for those actions it's currently a lot of work around.
Most custom inventory plugins use the org.bukkit.Player#performCommand() method to add this.

btab won't be accessable for those plugins when running 1.19 or higher.

Might also want to safe player's choice about scoreboards. Because it keeps resetting when people reconnect.

**Comment by NEZNAMY** [comment]
Plugins like CommandSync can do this.

**Comment by Whitescan** [comment]
> Plugins like CommandSync can do this. Feature requests are closed.

What about part that the plugin actually remembers if player's have it on or off?
Will that ever be a thing?

**Comment by NEZNAMY** [comment]
It does if you enable it in the config.
