### ISSUE TITLE
TAB-Bridge For Fabric?

### ISSUE THREAD

**Issue by Blobanium** [NEZNAMY/TAB-Bridge#21]
Hello.

I currently run a velocity proxy with backend servers running on fabric.

I was wanting to see if you are willing to make a fabric port of TAB-Bridge. That's all I want to know.

**Comment by Tanguygab** [comment]
TAB doesn't support Velocity so why do you need the bridge?
Also, since v4 TAB supports Fabric so you can directly put it there without requiring the bridge

**Comment by NEZNAMY** [comment]
What would bridge even do there? The main thing is PlaceholderAPI support, and fabric doesn't have any reliable placeholder plugin. World name detection doesn't work either.

**Comment by Onako2** [comment]
> TAB doesn't support Velocity so why do you need the bridge? Also, since v4 TAB supports Fabric so you can directly put it there without requiring the bridge
It does support. It is just not ready for production use.

**Comment by NEZNAMY** [comment]
Which features of bridge do you need on fabric?

**Comment by Tanguygab** [comment]
> > TAB doesn't support Velocity so why do you need the bridge? Also, since v4 TAB supports Fabric so you can directly put it there without requiring the bridge
> It does support. It is just not ready for production use.
> 

TAB doesn't work properly on Velocity, that's why we say it's not supported and we don't recommend it. Use it at your own risk but we won't and can't help you with any issue you may encouter.
