### ISSUE TITLE
TabAPI

### ISSUE THREAD

**Issue by Yacka03** [NEZNAMY/TAB-Bridge#22]
Hello i want to change my tab nickname in 1.19.4+ can this project help me for that if so what are the classes i need for that i can code but not have understanding of reflection

**Comment by NEZNAMY** [comment]
Bridge has nothing to do with tablist nicknames.

**Comment by Yacka03** [comment]
You have a plugin named Namer with a plugin.yml
name: Namer
description: Changes the name of players
main: me.perotin.namer.Namer
version: 1.2
commands:
   namer:
      usage: /namer <player> <new name>
      description: Sets a new name for player that can be more than two words and up to 16 characters!
   resetname:
      usage: /resetname <player>
      description: Resets a player's name to what it was originally
   namerreload:
      usage: /namerreload
      description: Reloads the names.yml file

I dont have access to source code for this plugin can you send it to me thank you
I want to change tablist name  and name above player head 1.19.4+

**Comment by Yacka03** [comment]
I decompiled it and source code is this if you need it [
/https://www.mediafire.com/file/hbqrobhagt0mem9/Namer_1.2_1(1).zip.src.zip/file

**Comment by NEZNAMY** [comment]
What does that have to do with TAB-Bridge project?
