### ISSUE TITLE
Add ViaVersion handle

### ISSUE THREAD

**Issue by luapascoal** [NEZNAMY/TAB-Bridge#23]
Yes, I know that the TAB itself already has the ViaVersion handle, but my problem, in this case, is:

I need ViaVersion and the other Via plugins on my backend servers because my server is 1.19.4 but most players play on 1.8 so I need the plugins on the backend to improve gameplay on 1.8

With that, the TAB, which is in the bungee (since I run in multiple instances, so I need the global tablist) cannot get the player's version with ViaVersion. I saw that this can be a problem if I want to have a specific tag in Legacy versions and a nice tag in more updated versions.

I believe this feature can be enabled, for people who need it like me, and shared just like placeholders are.

Thank you for your attention.

**Comment by luapascoal** [comment]
(I'm a little new to Via plugins, I've been migrating to the new versions for a while and I have a network with more than 1,000 online only in 1.8, so I could be saying something very wrong)

**Comment by Tanguygab** [comment]
if TAB is on Bungee, it can get the player's version without Via

**Comment by luapascoal** [comment]
> if TAB is on Bungee, it can get the player's version without Via, check /btab parse %player-version% from Bungee console and you'll see it works

but that won't cause problems like it says on the wiki?

**Comment by Tanguygab** [comment]
it only causes issues is TAB is on Spigot and ViaVersion is on the proxy

**Comment by luapascoal** [comment]
> It only causes issues if TAB is on the backend and ViaVersion is on the proxy. As long as ViaVersion is on the backend, everything's fine.

Oh, ok. Thansk!

**Comment by NEZNAMY** [comment]
What issues are you currently experiencing that you believe are caused by incorrect version detection? And when does the parse command show incorrect version for players?

**Comment by luapascoal** [comment]
> What issues are you currently experiencing that you believe are caused by incorrect version detection? And when does the parse command show incorrect version for players?

Honestly, none yet, we are testing. But I was reading the wiki and I came across the warning asking to use via version

**Comment by NEZNAMY** [comment]
Which one? There is only one against VV on Bungee, nothing else.

**Comment by luapascoal** [comment]
> Which one? There is only one against VV on Bungee, nothing else.

Whats the problem?

**Comment by NEZNAMY** [comment]
`But I was reading the wiki and I came across the warning asking to use via version`
Where does the wiki warn you and tell you to use viaversion?
