### ISSUE TITLE
Velocity

### ISSUE THREAD

**Issue by kainlighty** [NEZNAMY/TAB-Bridge#25]
Is Velocity support available now? I don't like bungeecord, so it's important to me

**Comment by NEZNAMY** [comment]
Bridge is not a proxy plugin. It's a backend plugin.

**Comment by kainlighty** [comment]
That is, this plugin communicates with servers, like a proxy with a bukkit?

**Comment by NEZNAMY** [comment]
This is a backend plugin which communicates with TAB on proxy.
