### ISSUE TITLE
Bridge does not work on 1.20.2 players

### ISSUE THREAD

**Issue by xPoyraz** [NEZNAMY/TAB-Bridge#28]
PlaceholderAPI data is not updated for 1.20.2 players, but there is no problem for players who enter the same server with 1.20. 
For players on version 1.20.2, when I reload /btab, everything works instantly, so I guess the data is not refreshed instantly;

![image](https://github.com/NEZNAMY/TAB-Bridge/assets/80398232/2812c58c-b7e5-4413-90d5-877bb79bf59c)
![image](https://github.com/NEZNAMY/TAB-Bridge/assets/80398232/d2d4a168-97a2-4a64-acba-f4fe4c7cd8d2)

**Comment by xPoyraz** [comment]
> PlaceholderAPI data is not updated for 1.20.2 players, but there is no problem for players who enter the same server with 1.20. For players on version 1.20.2, when I reload /btab, everything works instantly, so I guess the data is not refreshed instantly;
> 
> ![image](https://user-images.githubusercontent.com/80398232/277144066-2812c58c-b7e5-4413-90d5-877bb79bf59c.png) ![image](https://user-images.githubusercontent.com/80398232/277144072-d2d4a168-97a2-4a64-acba-f4fe4c7cd8d2.png)

server version: 1.16.5
tab version: 4.8.0
tab bridge version: 3.1.7

**Comment by Tanguygab** [comment]
The latest TAB version of 4.0.7, are you sure you're using the right plugin?

**Comment by NEZNAMY** [comment]
Are you sure you actually are using 3.1.7 version of bridge? This issue was fixed there. You will also need latest version of TAB, which we know nothing about.

**Comment by xPoyraz** [comment]
> The latest TAB version of 4.0.7, are you sure you're using the right plugin?

I am using 4.0.8 builds, I wrote it wrong




> Are you sure you actually are using 3.1.7 version of bridge? This issue was fixed there. You will also need latest version of TAB, state of which on your server we know nothing about.
Yes I'm sure I'm using 3.1.7;
![image](https://github.com/NEZNAMY/TAB-Bridge/assets/80398232/ae17b67e-c924-4b19-b6a7-97a5fcd86a8f)

**Comment by NEZNAMY** [comment]
Do you have discord? I would send you a jar to test and don't want to make a full release if I don't even know if it will fix the issue.

**Comment by xPoyraz** [comment]
> Do you have discord? I would send you a jar to test and don't want to make a full release if I don't even know if it will fix the issue.

Ok I can test it, my discord name is "poyrazoglu"
