### ISSUE TITLE
Placeholder Error with ECloud Extension "Server"

### ISSUE THREAD

**Issue by MJonah** [NEZNAMY/TAB-Bridge#29]
Hello the Bridge Plugin is spamming this error when installing the "Server" Extension.

https://hastebin.com/share/alehiwijiw.ruby

Server Version: 1.20.2
Plugin Version: v3.1.7
Paper Build: 245

**Comment by NEZNAMY** [comment]
https://github.com/NEZNAMY/TAB/wiki/Placeholders#sync-refreshing
Please stop abusing issue tracker for support.
