### ISSUE TITLE
add support nametags

### ISSUE THREAD

**Issue by TOWUK** [NEZNAMY/TAB-Bridge#3]
please add to this plugin support nametags for bungee/velocity mode

**Comment by NEZNAMY** [comment]
Nametags are already supported on bungeecord.

**Comment by TOWUK** [comment]
> Nametags are already supported on bungeecord.

уже? для этого требуется tab-bridge plugin?

**Comment by TOWUK** [comment]
I compiled this plugin via **'mvn clean install'** and put it in the server plugins folder, did I do it right?

**Comment by TOWUK** [comment]
prefixes are still not displayed for players
![image](https://user-images.githubusercontent.com/28830162/154914042-6e3e260d-5c52-42e6-9508-08645b2890d1.png)

**Comment by TOWUK** [comment]
![image](https://user-images.githubusercontent.com/28830162/154915818-6fe15caf-1670-4b72-86ef-b4957bc0efa1.png)

**Comment by NEZNAMY** [comment]
Velocity isn't supported.

**Comment by TOWUK** [comment]
and you say it won't work on **velocity**? it's better than `bungeecord`

**Comment by NEZNAMY** [comment]
Yes, I am saying the plugin doesn't support velocity.
