### ISSUE TITLE
How to disable this?

### ISSUE THREAD

**Issue by xKefir** [NEZNAMY/TAB-Bridge#30]
Hello, some time ago I wanted to set bold names above the player's head - I succeeded and now I have a problem with the PVPManager plugin, it does not add the tab prefix and nickname above the player's head because of this

`[TAB-Bridge] Blocked attempt to add player x_Kefir into team PVP-eb9c1bf666b3`

How can i disable this?

**Comment by NEZNAMY** [comment]
```
 scoreboard-teams:
  enabled: false
```
Velocity does not have scoreboard API anyway.

**Comment by xKefir** [comment]
Now tagprefix: in groups.yml not working
