### ISSUE TITLE
TAB-Bridge v3.1.8 (placeholder-errors)

### ISSUE THREAD

**Issue by var1nthon** [NEZNAMY/TAB-Bridge#31]
Platform: https://paste.gg/p/var1nthon/45eb5eab03cf42a083ed732852ca98aa
JVM Flags: https://paste.gg/p/var1nthon/53063a48f43e486892bbce761dacd9d9
World: ![image](https://github.com/NEZNAMY/TAB-Bridge/assets/49745824/0bc13f3e-73b1-4d0d-b662-dc50ed7fe673)

Plugin: PlaceholderAPI-2.11.5.jar(spigot), TAB-Bridge v3.1.8.jar(spigot), TAB v4.0.9.jar(bungeecord)

TAB-Bridge v3.1.8 (placeholder-errors)
https://paste.gg/p/var1nthon/7f6db2d4dd0f4821a005aa9710b4b9d7

**Comment by NEZNAMY** [comment]
https://github.com/NEZNAMY/TAB/wiki/Placeholders#sync-refreshing ?
