### ISSUE TITLE
About overriding nametag visibility...

### ISSUE THREAD

**Issue by MATRIX-feather** [NEZNAMY/TAB-Bridge#32]
## Description
Hello, we met some difficulties in making integration with TAB-Bridge.

We want to hide the player's nametag for a certain time, but we can't find an API to do it.

Is there any API we can use? Or can we have one?

**Comment by NEZNAMY** [comment]
Bridge doesn't have any API, everything is done through the main plugin.

**Comment by MATRIX-feather** [comment]
I see... Thanks for reply.
