### ISSUE TITLE
Name tag doesn't show or hide as excepted with bridge

### ISSUE THREAD

**Issue by MATRIX-feather** [NEZNAMY/TAB-Bridge#33]
*The code we used to hide/show the name tag: [TabAdapter.java#L39](https://github.com/XiaMoZhiShi/FeatherMorph/blob/81e28bc253d806ed3a3c90c763b31a016dcdc3fa/src/main/java/xiamomc/morph/misc/integrations/tab/TabAdapter.java#L39)*

The tag hides as expected when TAB is only installed on the server:

https://github.com/NEZNAMY/TAB-Bridge/assets/55654482/b4053a6a-662b-491a-b5dd-8ea47a23c09c

But it sometimes doesn't when TAB is installed on both sides (proxy and the server), and the bridge on the server:

https://github.com/NEZNAMY/TAB-Bridge/assets/55654482/4faf9950-88f2-4c60-9033-a0e9a0c3108b

**Comment by NEZNAMY** [comment]
Your code is clearly bukkit code. Are you sure you are calling it the proxy where TAB is installed as well?

**Comment by MATRIX-feather** [comment]
Well... the code itself doesn't interact with the proxy, and it runs on the backend server

**Comment by NEZNAMY** [comment]
Show your code. This has nothing to do with bridge however.

**Comment by MATRIX-feather** [comment]
Sure: https://gist.github.com/MATRIX-feather/9601cad897dcfa91589bc07a921b87de

**Comment by NEZNAMY** [comment]
Disable unlimited nametag mode.

**Comment by MATRIX-feather** [comment]
Disabled, and the tag hides as expected

**Comment by NEZNAMY** [comment]
Does it work with backend installation instead of proxy?

**Comment by MATRIX-feather** [comment]
Yes, it works with the backend, but on proxy it doesn't

**Comment by NEZNAMY** [comment]
Unlimited nametag mode was marked for removal and no more bugs will be fixed. See https://gist.github.com/NEZNAMY/f4cabf2fd9251a836b5eb877720dee5c for more info.
