### ISSUE TITLE
Is there a way to enable or disable personal scoreboards on the backend server?

### ISSUE THREAD

**Issue by polang233** [NEZNAMY/TAB-Bridge#37]
For example, my TAB plugin is installed in BungeCord, but I want the Paper backend plugin to enable or disable the scoreboard on the proxy side. I couldn't find the corresponding API, is there a corresponding method?

**Comment by NEZNAMY** [comment]
No there isn't. Bridge has nothing to do with scoreboards, so your question is not even about the correct plugin.

**Comment by polang233** [comment]
Thank you
