### ISSUE TITLE
When the player continues to right-click with an item in the off-hand, there is a good chance that the mob will not take damage.

### ISSUE THREAD

**Issue by twseer67875** [NEZNAMY/TAB-Bridge#5]
When the player continues to right-click with an item in the off-hand, there is a good chance that the mob will not take damage.

After repeated tests, it was confirmed that it was the TAB-Bridge plug-in problem

Plugins (47): BBeeChecker, BetterRTP, BlockLocker, ChestSort, Chunky, ChunkyBorder, CoCoBeenBossBarHealth, CoCoBeenGriefPreventionTeleport, CoCoBeenPlaceholderPlugin, CoCoBeenPlayerSignItem, CoCoBeenServerTweaks, ColoredAnvils, CoreProtect, CoreProtectTNT, DeluxeMenus, DiscordSRV, Elevator, EntityMoneyDrop, Essentials, EssentialsSpawn, FarmControl, GriefPrevention, GriefPreventionTweaks, GSit, HolographicDisplays, InteractiveChat, InteractiveChatDiscordSrvAddon, LuckPerms, MarketPlace, MaSuiteCore, MaSuiteTeleports, Minepacks, MysqlPlayerDataBridge, OreReplacer, PlaceholderAPI, PlayerWarps, PlugManX (PlugMan), ProtocolLib, PvPManager, SafariNet, spark, Spartan, TAB-Bridge, UltimateTimber, Vault, VentureChat, WorldEdit

Server Version: 
[16:04:06 INFO]: This server is running Paper version git-Paper-283 (MC: 1.18.2) (Implementing API version 1.18.2-R0.1-SNAPSHOT) (Git: f8e8d6c)

Bungeecord Version: 
[16:05:33 INFO]: This server is running Waterfall version git:Waterfall-Bootstrap:1.18-R0.1-SNAPSHOT:739eda6:482 by md_5

TAB Version: TAB version 3.1.1 (Bungeecord)

TAB-Bridge Version: TAB-Bridge version 2.0.1

https://youtu.be/5L0kfg1sTIo

**Comment by NEZNAMY** [comment]
Config?

**Comment by twseer67875** [comment]
> Config?
[TAB_Config.zip](https://github.com/NEZNAMY/TAB-Bridge/files/8519611/TAB_Config.zip)

**Comment by NEZNAMY** [comment]
try
```
fix-pet-names:
  enabled: false
```

**Comment by twseer67875** [comment]
> try
> 
> ```
> fix-pet-names:
>   enabled: false
> ```

problem solved

But after closing it will encounter this problem
https://github.com/NEZNAMY/TAB/wiki/Feature-guide:-Pet-name-fix

**Comment by NEZNAMY** [comment]
Try https://github.com/NEZNAMY/TAB-Bridge/actions/runs/2194523029

**Comment by twseer67875** [comment]
> 

Problem solved perfectly
Thank u
